---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.vpa.name }}
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Values.vpa.name }}
  updatePolicy:
    updateMode: Initial
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: {{ .Values.resourcePolicy.minAllowed.cpu }}
          memory: {{ .Values.resourcePolicy.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.resourcePolicy.maxAllowed.cpu }}
          memory: {{ .Values.resourcePolicy.maxAllowed.memory }}
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits