variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - release
  - test
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true

release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  cache: []
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA $VERSION

test:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACKEND} -Dsonar.sources=backend/ -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${SONAR_LOGIN_BACKEND}
  allow_failure: true

# Стадия актуальна для деплоя docker контейнеров
# deploy:
#   stage: deploy
#   image: alpine:3.18
#   before_script:
#     - apk add openssh-client bash gettext
#     - eval $(ssh-agent -s)
#     - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#     - ssh-keygen -R ${DEV_HOST}
#     - ssh -o StrictHostKeyChecking=no ${DEV_USER}@${DEV_HOST} "mkdir -p /tmp/${CI_PROJECT_DIR}/backend/"
#     - envsubst < ./backend/deploy.sh|ssh ${DEV_USER}@${DEV_HOST}
#   script:
#     - echo "Deployment step is complete"

deploy:
  stage: deploy
  image: alpine/k8s:1.28.14
  environment:
    name: Kubernetes/backend
    url: http://vm.momo-store.cloud-ip.biz
  only:
    changes:
      - kubernetes/backend/**/*
      - backend/**/*
  before_script:
    - apk add gettext
  script:
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - pwd
    - ls -la
    - mkdir -p .kube
    - echo "$KUBECONFIG_BASE64"
    - echo "$KUBECONFIG_BASE64" | base64 -d > .kube/config
    - export KUBECONFIG=.kube/config
    - ls -la .kube/config
    - cat .kube/config
    - printenv
    - echo ${VERSION}
    - echo ${CI_REGISTRY_IMAGE}
    - envsubst < kubernetes/backend/secrets.yaml | kubectl apply -f -
    - envsubst < kubernetes/backend/deployment.yaml | kubectl apply -f -
    - envsubst < kubernetes/backend/service.yaml | kubectl apply -f -
    - envsubst < kubernetes/backend/vpa.yaml | kubectl apply -f -
  after_script:
    - rm -f .kube/config
