# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF6TUMwek5UcFhTbFJLVFhKU1FrdzBialkzTWxsaGRtNVljdz09IgogICAgICAgIH0KICAgIH0KfQ==

type: kubernetes.io/dockerconfigjson
